# Generated by Django 5.2.7 on 2026-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0005_alter_class_options_class_number_of_pupils_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybreakfasts',
            options={'verbose_name': 'Выбор завтрака на неделю', 'verbose_name_plural': 'Все выборы завтрака на неделю'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название блюда'),
        ),
    ]
